const http = require('http');

function postToTally(xml) {
    return new Promise((resolve, reject) => {
        const req = http.request('http://localhost:9000', {
            method: 'POST',
            headers: { 'Content-Type': 'text/xml', 'Content-Length': Buffer.byteLength(xml) }
        }, (res) => {
            let d = '';
            res.on('data', c => d += c);
            res.on('end', () => resolve(d));
        });
        req.on('error', reject);
        req.write(xml);
        req.end();
    });
}

function getResult(res) {
    return res.match(/<(CREATED|ERRORS|EXCEPTIONS|LINEERROR)>[^<]+<\/(CREATED|ERRORS|EXCEPTIONS|LINEERROR)>/g)?.join(' ');
}

async function main() {

    // ================================================================
    // MONTH 7 - October 2025 (20251031) - 4 employees
    // ================================================================
    // 1. Nayankumar Godhani: Gross 219.78, Tax 0, NICs 0, Net 219.78
    // 2. Parth: Gross 1196.58, Tax 29.80, Emp NICs 11.89, Emp'r NICs 116.94, Net 1154.89
    // 3. Pinal Godhani: Gross 219.78, Tax 0, NICs 0, Net 219.78
    // 4. Salil: Gross 1666.67, Tax 123.60, Emp NICs 0, Emp'r NICs 250.00, Net 1543.07
    const octXml = `
    <ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER>
    <BODY><IMPORTDATA><REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME></REQUESTDESC><REQUESTDATA>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251031</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Nayankumar Godhani - Month 7 - Oct 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Nayankumar Godhani Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-219.78</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Nayankumar Godhani Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>219.78</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251031</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Parth Kumar Patoliya - Month 7 - Oct 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1196.58</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-116.94</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>29.80</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employee NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>11.89</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>116.94</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1154.89</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251031</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Pinal Godhani - Month 7 - Oct 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Pinal Godhani Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-219.78</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Pinal Godhani Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>219.78</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251031</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Salil Anand - Month 7 - Oct 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1666.67</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>123.60</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1543.07</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
    </REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>`;

    console.log('Posting Month 7 - Oct 2025...');
    const octRes = await postToTally(octXml);
    console.log('Oct:', getResult(octRes));

    // ================================================================
    // MONTH 8 - November 2025 (20251130)
    // Nayankumar & Pinal: 0.00 all - SKIP
    // Parth: Gross 1074.48, Tax 5.20, Emp NICs 2.12, Emp'r NICs 98.62, Net 1067.16
    // Salil: Gross 1666.67, Tax 123.80, Emp NICs 61.07, Emp'r NICs 250.00, Net 1481.80
    // ================================================================
    const novXml = `
    <ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER>
    <BODY><IMPORTDATA><REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME></REQUESTDESC><REQUESTDATA>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251130</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Parth Kumar Patoliya - Month 8 - Nov 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1074.48</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-98.62</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>5.20</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employee NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>2.12</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>98.62</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1067.16</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251130</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Salil Anand - Month 8 - Nov 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1666.67</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>123.80</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employee NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>61.07</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1481.80</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
    </REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>`;

    console.log('Posting Month 8 - Nov 2025...');
    const novRes = await postToTally(novXml);
    console.log('Nov:', getResult(novRes));

    // ================================================================
    // MONTH 9 - December 2025 (20251231) - 4 employees
    // Nayankumar: Gross 1001.22, Tax 0, NICs 0, Emp'r NICs 87.63, Net 1001.22
    // Parth: Gross 976.80, Tax -14.20 (REFUND), NICs 0, Emp'r NICs 83.97, Net 991.00
    // Pinal: Gross 1001.22, Tax 0, NICs 0, Emp'r NICs 87.63, Net 1001.22
    // Salil: Gross 1666.67, Tax 123.60, Emp NICs 133.33, Emp'r NICs 250.00, Net 1409.74
    // ================================================================
    const decXml = `
    <ENVELOPE><HEADER><TALLYREQUEST>Import Data</TALLYREQUEST></HEADER>
    <BODY><IMPORTDATA><REQUESTDESC><REPORTNAME>Vouchers</REPORTNAME></REQUESTDESC><REQUESTDATA>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251231</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Nayankumar Godhani - Month 9 - Dec 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Nayankumar Godhani Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1001.22</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-87.63</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>87.63</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Nayankumar Godhani Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1001.22</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251231</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Parth Kumar Patoliya - Month 9 - Dec 2025 (Tax Refund -14.20)</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-976.80</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-83.97</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-14.20</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>83.97</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Parth Kumar Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>991.00</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251231</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Pinal Godhani - Month 9 - Dec 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Pinal Godhani Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1001.22</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-87.63</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>87.63</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Pinal Godhani Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1001.22</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
      <TALLYMESSAGE xmlns:UDF="TallyUDF"><VOUCHER VCHTYPE="Journal" ACTION="Create">
        <DATE>20251231</DATE><VOUCHERTYPENAME>Journal</VOUCHERTYPENAME>
        <NARRATION>Payroll - Salil Anand - Month 9 - Dec 2025</NARRATION>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-1666.67</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs</LEDGERNAME><ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE><AMOUNT>-250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>HMRC PAYE Tax Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>123.60</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employee NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>133.33</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Employer NICs Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>250.00</AMOUNT></ALLLEDGERENTRIES.LIST>
        <ALLLEDGERENTRIES.LIST><LEDGERNAME>Salil Anand Salary Payable</LEDGERNAME><ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE><AMOUNT>1409.74</AMOUNT></ALLLEDGERENTRIES.LIST>
      </VOUCHER></TALLYMESSAGE>
    </REQUESTDATA></IMPORTDATA></BODY></ENVELOPE>`;

    console.log('Posting Month 9 - Dec 2025...');
    const decRes = await postToTally(decXml);
    console.log('Dec:', getResult(decRes));

    console.log('\n=== SUMMARY ===');
    console.log('Month 7 Oct:', octRes.includes('<CREATED>4</CREATED>') ? '✅ 4 vouchers' : getResult(octRes));
    console.log('Month 8 Nov:', novRes.includes('<CREATED>2</CREATED>') ? '✅ 2 vouchers (Parth + Salil only)' : getResult(novRes));
    console.log('Month 9 Dec:', decRes.includes('<CREATED>4</CREATED>') ? '✅ 4 vouchers' : getResult(decRes));
}

main().catch(console.error);
